name: Build APK Emulator EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build Project
      run: ./gradlew build --no-daemon

    # ИСПРАВЛЕНО: Теперь параметр --input указывает на launcher/build/jpackage
    - name: Package EXE
      run: |
        jpackage --type app-image --input launcher/build/jpackage --main-jar launcher.jar --main-class com.emulator.launcher.Main --dest dist --name "APKEmulator Launcher"
      shell: bash

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-APKEmulator-Launcher
        path: dist/APKEmulator Launcher/
